### PR TITLE
Scan party/raid targets to find guids for nameplates.

### PR DESCRIPTION
**Pull request by salt-die**
Nameplates dont have guid information attached to them. Normally, one has to wait for a mouseover/target/focus event to match a guid to a nameplate. This adds another method -- when health changes on a nameplate, if it doesn't have a guid, then scan party/raid members' targets. If one of those targets health and max health matches a nameplate without a guid, then assign that guid to the nameplate.

### CODE REVIEW

**Comment by andrew6180** [comment]
This should be almost completely unnecessary with some new nameplate stuff coming. We can already map a nameplate to a guid and retrieve the frame, just working on allowing all unit tokens. 

Cast bars can also be fixed similar to projet zidras soon.

Will leave this open and discuss best way to do this when those are implemented

**Comment by salt-die** [comment]
If guid information can be fetched from nameplate -- this entire module can probably be simplified.

**Comment by andrew6180** [comment]
Anything that takes a unit token would be usable. Ex UnitAura

**Comment by andrew6180** [comment]
`GetNamePlateForUnit(unitToken)` 

C_Hook-able events
`NAME_PLATE_UNIT_ADDED:  nameplate#`
`NAME_PLATE_UNIT_REMOVED: nameplate#`

the `nameplate#` token can be passed into anything that requires a unit token

Examlpe:
```lua
C_Hook:Register(C_NamePlate, "NAME_PLATE_UNIT_ADDED")

function C_NamePlate:NAME_PLATE_UNIT_ADDED(unit)
    local locClass, engClass, locRace, engRace, gender, name, server = GetPlayerInfoByGUID(UnitGUID(unit))
end
```


Would anything else be needed for what you're trying to accomplish?

**Comment by salt-die** [comment]
If `UnitGUID("nameplateN")` is added, then we'd be good to go. We could update auras on nameplates as soon as they're created instead of searching through targets/party/pets/etc hoping to find a match.

**Comment by andrew6180** [comment]
Will this PR be necessary then if that's added?

**Comment by salt-die** [comment]
No. A new PR though with a lot of the module deleted will be submitted!

**Comment by andrew6180** [comment]
closing then

**Pull request closed without merging**
